## This is only a single container right now but in future this should bring up supporting services needed for development ie: postgres, audit service ect.
version: '3'
services:
  reviewer-mocks:
    image: liberoadmin/reviewer-mocks:latest
    ports:
      - "${CONTINUUM_LOGIN_PORT}:3003"
    healthcheck:
      test: "curl localhost:3003/health"
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./config/config.example.json:/etc/reviewer/config.json:z