## This is only a single container right now but in future this should bring up supporting services needed for development ie: postgres, audit service ect.
version: '3'
services:
  reviewer-mocks:
    image: node:10
    ports:
      - "${REVIEWER_MOCKS_PORT:-3003}:3003"
    working_dir: "/src"
    command: ["bash", "-c", "yarn && yarn run start:dev"]
    healthcheck:
      test: "curl localhost:3003/health"
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      PORT: "3003"
      CONTINUUM_LOGIN_JWT_SECRET: "${CONTINUUM_LOGIN_JWT_SECRET}"
      CONTINUUM_LOGIN_REDIRECT_URL: "${CONTINUUM_LOGIN_REDIRECT_URL}"
    volumes:
      - ./config:/etc/reviewer/config.json
      - ./:/src/:z
    networks:
      - infra_api

networks:
  infra_api:
    external:
      name: "infra_api"