## This is only a single container right now but in future this should bring up supporting services needed for development ie: postgres, audit service ect.
version: '3'
services:
  reviewer-mocks:
    image: libero/reviewer-mocks:local
    ports:
      - "${CONTINUUM_LOGIN_PORT:-3003}:3003"
    environment: 
      DATA_DIRECTORY_PATH: "/etc/mock-data/"
    volumes:
      - ./config/config.example.json:/etc/reviewer/config.json:z
      - ./mock-data/someOtherMockData:/etc/mock-data/ 