version: '3'
services:
  mock-continuum-login:
    build:
      context: "."
      dockerfile: 'Dockerfile'
      args:
        image_tag: ${IMAGE_TAG}
    image: libero/mock-continuum-login:${IMAGE_TAG}
