name: semver Tagging

on:
  push:
    tags:
      - v*

jobs:
  tag-master-with-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - run: |
          docker pull liberoadmin/reviewer-mocks:master-${{ github.sha }}
          ./scripts/github/retag-and-push.sh reviewer-mocks master-${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
